// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"SNZ_FirebaseSave","status":true,"description":"FirebaseというWebサービスを使用し、クラウドセーブ（オンラインセーブ）を実現。","parameters":{"savedesc":"ソーシャルアカウントと連携すると<br>セーブのバックアップができます。<br>勝手に投稿することはありません。","usetwitter":"false","usefacebook":"false","starttext":"Press Start","startfont":"{\"fontface\": \"\", \"size\":\"52\", \"bold\":\"false\", \"italic\":\"false\", \"color\": \" rgba(255,255,255,1.0)\"}","startse":"{\"name\":\"\", \"volume\": \"90\", \"pitch\":\"100\", \"pan\":\"0\"}","firebaseconfig":"{\"apiKey\":\"AIzaSyBp_qOC9_30KXP5j9UWk32ZJ0ikOnrZ-84\",\"authDomain\":\"rpg-maker-mv-online.firebaseapp.com\",\"databaseURL\":\"https://rpg-maker-mv-online-default-rtdb.firebaseio.com\",\"projectId\":\"rpg-maker-mv-online\",\"storageBucket\":\"rpg-maker-mv-online.appspot.com\",\"messagingSenderId\":\"575672488768\"}"}},
{"name":"Community_Basic","status":true,"description":"Plugin used to set basic parameters.","parameters":{"cacheLimit":"10","screenWidth":"816","screenHeight":"624","changeWindowWidthTo":"","changeWindowHeightTo":"","renderingMode":"webgl","alwaysDash":"off"}},
{"name":"DevToolsManage","status":false,"description":"デベロッパツール管理プラグイン","parameters":{"開始時に起動":"ON","常に前面表示":"OFF","デベロッパツール表示位置":"0,0,800,600","最小化切替キー":"F8","リロードキー":"F12","画面の左寄せキー":"","高速化切替キー":"","強制戦闘勝利キー":"","スクリプト実行キー":"","フリーズキー":"","FPS表示":"OFF","タイトルカット":"OFF","高速開始":"OFF","高速スピード":"2","モバイル偽装":"OFF","メニューバー表示":"ON","クリックメニュー":"-1"}},
{"name":"111_InputForm","status":true,"description":"フォーム作って文字入力（修正版）","parameters":{}},
{"name":"DTextPicture","status":true,"description":"動的文字列ピクチャ生成プラグイン","parameters":{}},
{"name":"TMNamePop","status":true,"description":"イベントの頭上に文字列を表示する機能を追加します。","parameters":{"backOpacity":"96","fontSize":"20","fontOutlineWidth":"4","fontOutlineColor":"rgba(0, 0, 0, 0.5)","width":"240","useRoundRect":"0","roundRectRadius":"6"}},
{"name":"QuickMove","status":true,"description":"歩行とジャンプを軽快に(2000風に)します。","parameters":{}},
{"name":"OnlineAvatar","status":true,"description":"Firebaseを使ってプレイヤーをオンライン同期します。","parameters":{"apiKey":"AIzaSyBp_qOC9_30KXP5j9UWk32ZJ0ikOnrZ-84","authDomain":"rpg-maker-mv-online.firebaseapp.com","databaseURL":"https://rpg-maker-mv-online-default-rtdb.firebaseio.com","avatarEvent":"1","syncSwitchStart":"11","syncSwitchEnd":"20","syncVariableStart":"11","syncVariableEnd":"20"}},
{"name":"DataCacheBlocker","status":true,"description":"キャッシュを阻止します。（dataフォルダのみ）","parameters":{}},
{"name":"SymbolReplacer","status":true,"description":"ファイル名の!と$を別の語に置き換えます。","parameters":{"method":"restore","exclamationmark":"Exc_","dollar":"Dol_"}},
{"name":"MakeScreenCapture","status":true,"description":"画面キャプチャ管理プラグイン","parameters":{"PNGキャプチャキー":"F6","JPEGキャプチャキー":"F7","WEBPキャプチャキー":"F10","ファイル名":"image","出力場所":"/captures","保存形式":"png","連番桁数":"2","タイムスタンプ":"ON","署名":"","署名サイズ":"22","署名画像":"","実行間隔":"0","効果音":"Flash1"}},
{"name":"MessageWindowHidden","status":true,"description":"メッセージウィンドウ一時消去プラグイン","parameters":{"ボタン名称":"control"}},
{"name":"AdjustPictureGraphical","status":true,"description":"ピクチャのグラフィカルな位置調整プラグイン。\nパラメータを変更したら「プロジェクトの保存」（Ctrl+S）","parameters":{"グリッドサイズ":"48","テストマップID":"-1"}},
{"name":"TMAutoNewGame","status":false,"description":"起動時に自動ではじめからゲームを開始します。\r\nWeb用ミニゲームなど、タイトルが不要な場合に使えます。","parameters":{"autoNewGame":"1","allwaysOnTop":"0","autoDevTool":"0"}},
{"name":"HyperLink","status":true,"description":"ゲーム中に外部ページへのリンクを貼ります。","parameters":{"description":"Webサイトへのリンク"}},
{"name":"DebugMonitor","status":true,"description":"スイッチ・変数の状態を画面上にリアルタイム表示します。","parameters":{"monitorX":"0","monitorY":"100","monitorW":"240"}},
{"name":"AudioSource","status":true,"description":"音源と聞き手の位置関係に応じて自動的に音量・位相を調節します。","parameters":{"listener":"screen","decay":"85","pan":"10","cutoff":"1"}},
{"name":"LoopTagChecker","status":true,"description":"bgmとbgsの音楽ファイルにループタグがついているかチェックします。","parameters":{"folder":"both","display":"both"}},
{"name":"ParallelBgs","status":true,"description":"BGS並行演奏プラグイン","parameters":{}},
{"name":"EasingPicture","status":true,"description":"ピクチャーの移動パターンを増やします。","parameters":{}},
{"name":"TimeEvent","status":true,"description":"時間の経過に応じてイベントを起こします。","parameters":{}},
{"name":"MessageCount","status":true,"description":"文章だけの長いシーンを検出します。","parameters":{"warningCount":"10"}},
{"name":"TMNamePop1","status":true,"description":"イベントの頭上に文字列を表示する機能を追加します。","parameters":{"backOpacity":"96","fontSize":"20","fontOutlineWidth":"4","fontOutlineColor":"rgba(0, 0, 0, 0.5)","width":"160","useRoundRect":"0","roundRectRadius":"6"}}
];
